name: Contribuciones manuales

on:
  push: # Se ejecuta cada vez que haces un push al repositorio

jobs:
  auto-contrib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
      
      - name: Realizar contribución
        run: |
          echo "Contribución automática: $(date)" >> README.md
      
      - name: Commit y push
        uses: EndBug/add-and-commit@v7
        with:
          message: "Contribución automática"
